### ISSUE TITLE
why the generated post is not shown in the homepage?

### ISSUE THREAD

**Issue by luckypoem** [curry-club-aux/curry-club-augsburg.de#65]
hi.

i setup the blog: http://cca.bright.biz.st/ ,and i generated a post: http://cca.bright.biz.st/posts/2016-11-09-vbcoz-i-love-u.html ,but this post is not shown in the homepage,why?

tks

**Comment by luckypoem** [comment]
i visit the site http://cca.bright.biz.st/  in another pc,it's normal.so i know the issue is caused by the cache in browser.

another question: how to delete the contents above "blog" section in my site?

**Comment by iblech** [comment]
Hi luckypoem!

We're happy that our small blogging system suits you. :-) It's kind of a surprise to us, because we wrote it just for our personal needs. However you are welcome to use it, as it's MIT licensed.

You can delete the contents above the "blog" section by editing `index.html`. Remove everything up to line 69, so that the first line of the truncated file is:

    $partial("templates/post-list.html")$

This line is the command which includes the list of posts.

Cheers,
Ingo

PS: Maybe you want to change the logo of your blog. You can do this by modifying the `<img>` tag in line 18 of `templates/default.html`.

**Comment by luckypoem** [comment]
@iblech ，thank u.now it's ok

**Comment by iblech** [comment]
Great! Then I'm closing the issue. We wish you happy blogging!

By the way, you can remove old blog posts simply by deleting the corresponding files in the `posts` subdirectory.
